# Drug Combination Prediction Model Configuration

model:
  gene_dim: 5000              # Number of genes in expression profile
  latent_dim: 20              # Latent dimension for autoencoder
  autoencoder_hidden: [1000, 200]  # Hidden layers for autoencoder
  predictor_hidden: [64, 128, 64]   # Hidden layers for combination predictor
  use_attention: false        # Whether to use attention mechanisms

training:
  # Autoencoder training
  ae_epochs: 100
  ae_lr: 0.001
  
  # Full model training
  full_epochs: 200
  full_lr: 0.0005
  
  # General training parameters
  batch_size: 32
  weight_decay: 0.0001
  seed: 42
  
  # Data augmentation
  use_symmetry_augmentation: true
  
  # Early stopping
  patience: 20
  min_delta: 0.0001

data:
  # Data preprocessing
  normalize_method: "standard"  # "standard", "minmax", "robust"
  use_differential: true        # Use differential expression vs baseline
  
  # Data splits
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  
  # Data filtering
  min_expression_threshold: 0.1
  max_variance_threshold: null  # Filter high variance genes if needed

evaluation:
  metrics:
    - "mae"           # Mean Absolute Error
    - "mse"           # Mean Squared Error
    - "r2"            # R-squared
    - "pearson"       # Pearson correlation
    - "spearman"      # Spearman correlation
  
  # Gene-wise evaluation
  gene_wise_analysis: true
  top_k_genes: 100    # Analyze top K most important genes

# Experiment tracking
wandb:
  project: "drug-combo-prediction"
  tags: ["pytorch", "gene-expression", "drug-combination"]

# Hardware
device: "auto"  # "auto", "cpu", "cuda"
num_workers: 4